package frc.robot.subsystems;

import com.ctre.phoenix.ErrorCode;
import com.ctre.phoenix.led.CANdle;
import com.ctre.phoenix.led.CANdleConfiguration;
import com.ctre.phoenix.led.CANdleFaults;
import com.ctre.phoenix.led.RainbowAnimation;

/*public class ledSubsystem {
     CANdle candle = new CANdle(0); // creates a new CANdle with ID 0

 CANdleConfiguration config = new CANdleConfiguration();
 config.LEDType(CANdle.LEDstripType rgb); // set the strip type to RGB
 config.brightnessScalar = 0.5; // dim the LEDs to half brightness
 candle.configAllSettings(config);

 candle.setLEDs(0, 255, 0, 0, 10); // set the CANdle LEDs to green


 ErrorCode error = candle.getLastError(); // gets the last error generated by the CANdle
 CANdleFaults faults = new CANdleFaults();
 ErrorCode faultsError = candle.getFaults(faults); // fills faults with the current CANdle faults; returns the last error generated
}*/
